server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: film-service
          uri: lb://film-service
          predicates:
            - Path=/film/**
        - id: media-service
          uri: lb://media-service
          predicates:
            - Path=/media/**
        - id: app
          uri: lb://app
          predicates:
            - Path=/app/**
    discovery:
      client:
        simple:
          instances:
            film-service:
              - uri: http://localhost:8081
            media-service:
              - uri: http://localhost:8082
            app:
              - uri: http://localhost:8083
  profiles:
    active: default

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
