name: CinemaX Gradle Build

on:
  push:
  workflow_dispatch:

jobs:
  build-gradle:

    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Build
        run: ./gradlew build --no-daemon
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: |
            build/test-results/test/*.xml
      - name: Checkstyle
        if: always()
        uses: jwgmeligmeyling/checkstyle-github-action@master
        with:
          path: 'build/reports/checkstyle'
      - uses: actions/upload-artifact@v3
        with:
          name: Package
          path: build/libs
      - name: Publish package
        uses: gradle/gradle-build-action@749f47bda3e44aa060e82d7b3ef7e40d953bd629
        with:
          arguments: publish
        env:
          GITHUB_TOKEN: ${{ secrets.JAVA_TOKEN }}
      - name:
        if: ${{ failure() }}
        run: echo "Package was not deployed. Update artifact version and rerun."