name: CinemaX Gradle Build

on:
  push:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-gradle:

    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Build
        run: ./gradlew build

      - name: Store reports
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: reports
          path: |
            **/build/reports/
            **/build/test-results/

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: CinemaX
          path: build/libs